package amberdb.sql;


import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;

import java.util.ArrayList;
import java.util.List;


public abstract class LookupsSchema {

    /*
     * Lookup table - stores simple (key, code, value) reference data
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS lookups ("
            + "id        bigint(11) PRIMARY KEY AUTO_INCREMENT, "
            + "name      varchar(50), "
            + "code      varchar(100), "
            + "value     varchar(255), "
            + "deleted   varchar(1) default 'N' )")
    public abstract void createLookupTable();
    
    /*
     * Link lookups table - stores relationships between 2 lookups
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS carrier_algorithm ("
            + "linkId        bigint(11) PRIMARY KEY AUTO_INCREMENT,"
            + "name      varchar(50), "
            + "carrierId       bigint(11), "
            + "algorithmId       bigint(11) )")
    public abstract void createCarrierAlgorithmTable();
    

    /*
     * Tools lookup table - stores tools related reference data
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS tools ("
            + "id          int(11), "
            + "name        varchar(255), "
            + "resolution  varchar(255), "
            + "notes       varchar(4000), "
            + "serialNumber varchar(255), "
            + "toolTypeId int(11), " 
            + "toolCategoryId int(11), "
            + "materialTypeId int(11), "
            + "commitTime  varchar(20), "
            + "commitUser  varchar(50), "
            + "deleted   varchar(1) default 'N' )")
    public abstract void createToolsTable();
    
    @SqlUpdate(
            "CREATE INDEX lookups_id_idx "
            + "ON lookups(id, deleted)")
    public abstract void createLookupsIdIndex();
    
    @SqlUpdate(
            "CREATE INDEX carrier_algorithm_id_idx "
            + "ON carrier_algorithm(linkId)")
    public abstract void createCarrierAlgorithmLinkIdIndex();
    
    @SqlUpdate(
            "CREATE INDEX carrier_algorithm_carrier_name_idx "
            + "ON carrier_algorithm(name, carrierId)")
    public abstract void createCarrierAlgorithmIndex();
    
  
    
    @SqlUpdate(
            "CREATE INDEX lookups_name_idx "
            + "ON lookups(name, deleted)")
    public abstract void createLookupsNameIndex();
    
    @SqlUpdate(
            "CREATE INDEX lookups_name_code_idx "
            + "ON lookups(name, code, deleted)")
    public abstract void createLookupsNameCodeIndex();
    
    @SqlUpdate(
            "CREATE INDEX tools_id_idx "
            + "ON tools(id, deleted)")
    public abstract void createToolsIdIndex();
    
    @SqlUpdate(
            "CREATE INDEX tools_tool_type_idx "
            + "ON tools(toolTypeId, deleted)")
    public abstract void createToolsToolTypeIdIndex();
    
    @SqlUpdate(
            "CREATE INDEX tools_tool_category_idx "
            + "ON tools(toolCategoryId, deleted)")
    public abstract void createToolsToolCategoryIdIndex();
    
    @SqlUpdate(
            "CREATE INDEX tools_material_type_idx "
            + "ON tools(materialTypeId, deleted)")
    public abstract void createToolsMaterialTypeIdIndex();
    

    /*
     * General lookups
     */
    @SqlUpdate(
      "INSERT INTO lookups (name, code) VALUES"
      + "('accessCondition', 'Restricted'),"
      + "('accessCondition', 'Unrestricted'),"        
      + "('accessCondition', 'Internal access only'),"
      + "('internalAccessCondition', 'Open'),"
      + "('internalAccessCondition', 'Restricted'),"        
      + "('internalAccessCondition', 'Closed'),"      
      + "('copyrightStatus', 'Out of Copyright'),"
      + "('copyrightStatus', 'In Copyright'),"
      + "('copyrightStatus', 'No known copyright restrictions'),"
      + "('copyrightStatus', 'Mixed copyright'),"
      + "('copyrightStatus', 'Perpetual'),"
      + "('carrier', 'File system'),"
      + "('carrier', 'Working Reel'),"
      + "('carrier', 'User Cassette'),"
      + "('carrier', 'Online'),"
      + "('carrier', 'CD-R'),"
      + "('carrier', 'CD-ROM'),"
      + "('carrier', 'Second copy'),"
      + "('carrier', 'CD Archive'),"
      + "('carrier', 'CD Filtered'),"
      + "('carrier', 'Preservation Reel'),"
      + "('carrier', 'Safety DAT'),"
      + "('carrier', 'Cassette A'),"
      + "('carrier', 'Cassette B'),"
      + "('carrier', 'DAT'),"
      + "('carrier', 'Multitrack-ADAT'),"
      + "('carrier', 'Multitrack-DTRS'),"
      + "('carrier', 'Reel A'),"
      + "('carrier', 'Reel B'),"
      + "('carrier', 'CD Duplicate'),"
      + "('carrier', 'User CD'),"
      + "('carrier', 'Second Duplicate'),"
      + "('carrier', 'DVD Archive'),"
      + "('carrier', 'Safety Reel'),"
      + "('carrier', 'Microcassette'),"
      + "('carrier', 'NONE'),"
      + "('acquisitionStatus', 'CURRENT'),"
      + "('acquisitionStatus', 'BACKLOG'),"
      + "('acquisitionStatus', 'MS'),"
      + "('acquisitionCategory', 'Social History'),"
      + "('acquisitionCategory', 'Eminent Australians'),"
      + "('acquisitionCategory', 'Folklore'),"
      + "('acquisitionCategory', 'Others'),"
      + "('segmentIndicator', 'Non-timed'),"
      + "('segmentIndicator', 'Timed'),"
      + "('bitDepth', '8'),"
      + "('bitDepth', '12'),"
      + "('bitDepth', '14'),"
      + "('bitDepth', '16'),"
      + "('bitDepth', '18'),"
      + "('bitDepth', '20'),"
      + "('bitDepth', '22'),"
      + "('bitDepth', '24'),"
      + "('orientation', 'Portrait'),"     
      + "('orientation', 'Landscape'),"
      + "('colourProfile', 'Within image'),"
      + "('colourProfile', 'External'),"
      + "('surface', 'Enhanced Azo'),"
      + "('surface', 'C-CrO2'),"
      + "('surface', 'C-Fe2O3'),"
      + "('surface', 'C-Metal'),"
      + "('surface', 'Cyanine'),"
      + "('surface', 'DOSS'),"
      + "('surface', 'Metal Azo'),"
      + "('surface', 'Pthalocyanine'),"
      + "('surface', 'Pthalocyanine Al'),"
      + "('surface', 'T-Acetate'),"
      + "('surface', 'T-Paper'),"
      + "('surface', 'T-Polyester'),"
      + "('surface', 'T-PVC'),"
      + "('surface', 'Unsure'),"
      + "('carrierCapacity', '2 min'),"
      + "('carrierCapacity', '5 min'),"
      + "('carrierCapacity', '12 min'),"
      + "('carrierCapacity', '30 min'),"
      + "('carrierCapacity', '40 min'),"
      + "('carrierCapacity', '45 min'),"
      + "('carrierCapacity', '46 min'),"
      + "('carrierCapacity', '60 min'),"
      + "('carrierCapacity', '63 min'),"
      + "('carrierCapacity', '65 min'),"
      + "('carrierCapacity', '74 min'),"
      + "('carrierCapacity', '80 min'),"
      + "('carrierCapacity', '90 min'),"
      + "('carrierCapacity', '95 min'),"
      + "('carrierCapacity', '96 min'),"
      + "('carrierCapacity', '120 min'),"
      + "('carrierCapacity', '122 min'),"
      + "('carrierCapacity', '125 min'),"
      + "('carrierCapacity', '180 min'),"
      + "('carrierCapacity', '650 MB'),"
      + "('carrierCapacity', '4.7 GB'),"
      + "('reelSize', '2in'),"
      + "('reelSize', '3in IEC'),"
      + "('reelSize', '4in IEC'),"
      + "('reelSize', '5in IEC'),"
      + "('reelSize', '5in NAB'),"
      + "('reelSize', '6in IEC'),"
      + "('reelSize', '7in IEC'),"
      + "('reelSize', '7in NAB'),"
      + "('reelSize', '8.25in IEC'),"
      + "('reelSize', '10in NAB'),"
      + "('reelSize', '10in IEC'),"
      + "('reelSize', '12 min'), "
      + "('reelSize', '120 min'), "
      + "('reelSize', '122 min'), "
      + "('reelSize', '125 min'), "
      + "('reelSize', '180 min'), "
      + "('reelSize', '2 min'), "
      + "('reelSize', '30 min'), "
      + "('reelSize', '40 min'), "
      + "('reelSize', '45 min'), "
      + "('reelSize', '46 min'), "
      + "('reelSize', '5 min'), "
      + "('reelSize', '60 min'), "
      + "('reelSize', '63 min'), "
      + "('reelSize', '65 min'), "
      + "('reelSize', '650MB'), "
      + "('reelSize', '74 min'), "
      + "('reelSize', '90 min'), "
      + "('reelSize', '95 min'), "
      + "('reelSize', '96 min'), "
      + "('reelSize', '80 min'), "
      + "('reelSize', '4.7 GB'), "
      + "('channel', '0.5'),"
      + "('channel', '1'),"
      + "('channel', '2'),"
      + "('channel', '4'),"
      + "('channel', '8'),"
      + "('channel', '16'),"
      + "('channel', '24'),"
      + "('speed', '2.38 cm/s'),"
      + "('speed', '4.76 cm/s'),"
      + "('speed', '9.5 cm/s'),"
      + "('speed', '19.05 cm/s'),"
      + "('speed', '38.1 cm/s'),"
      + "('speed', '76.2 cm/s'),"
      + "('thickness', 'Double play'),"
      + "('thickness', 'Long play'),"
      + "('thickness', 'Standard'),"
      + "('thickness', 'Triple play'),"
      + "('brand', 'EMITAPE 77/6'),"
      + "('brand', 'TDK 150'),"
      + "('brand', 'Scotch 131'),"
      + "('brand', 'AGFA PE 46'),"
      + "('brand', 'ACV'),"
      + "('brand', 'admark'),"
      + "('brand', '3M 807'),"
      + "('brand', 'ACME'),"
      + "('brand', 'AGFA'),"
      + "('brand', 'AGFA CARAT FeCr'),"
      + "('brand', 'AGFA DA DAT'),"
      + "('brand', 'AGFA DAT'),"
      + "('brand', 'AGFA FeI-S'),"
      + "('brand', 'AGFA FERRO COLOR'),"
      + "('brand', 'AGFA FERROCOLOR'),"
      + "('brand', 'AGFA FS'),"
      + "('brand', 'AGFA FS 396'),"
      + "('brand', 'AGFA GEVAERT'),"
      + "('brand', 'AGFA -GEVAERT PE36'),"
      + "('brand', 'AGFA Magnetonband'),"
      + "('brand', 'AGFA Magnetonband PER 525'),"
      + "('brand', 'AGFA PE 31'),"
      + "('brand', 'AGFA PE 36'),"
      + "('brand', 'AGFA PE 38'),"
      + "('brand', 'AGFA PE 4'),"
      + "('brand', 'AGFA PE 41'),"
      + "('brand', 'AGFA PE 65'),"
      + "('brand', 'AGFA PEM 369'),"
      + "('brand', 'AGFA PEM 468'),"
      + "('brand', 'AGFA PEM 469'),"
      + "('brand', 'AGFA PER'),"
      + "('brand', 'AGFA PER 368'),"
      + "('brand', 'AGFA PER 468'),"
      + "('brand', 'AGFA PER 525'),"
      + "('brand', 'AGFA PER 528'),"
      + "('brand', 'AGFA PER 555'),"
      + "('brand', 'AGFA SM'),"
      + "('brand', 'AGFA SUPER C60+6'),"
      + "('brand', 'AGFA SUPER COLOR'),"
      + "('brand', 'AGFA SUPERCHROM'),"
      + "('brand', 'AGFA WOLFEN'),"
      + "('brand', 'AGFA-GEVAERT'),"
      + "('brand', 'AGFA-GEVAERT 65'),"
      + "('brand', 'AGFA-GEVAERT SM'),"
      + "('brand', 'AIWA'),"
      + "('brand', 'AIWA DAT'),"
      + "('brand', 'AKAI'),"
      + "('brand', 'AKAI AT-5S'),"
      + "('brand', 'AKAI Ferro Extra I'),"
      + "('brand', 'AKAI HX'),"
      + "('brand', 'Allegro'),"
      + "('brand', 'ALMAG'),"
      + "('brand', 'ALPHA'),"
      + "('brand', 'AMCOLOR'),"
      + "('brand', 'AMERICAN'),"
      + "('brand', 'American Recording tape'),"
      + "('brand', 'AMPEX'),"
      + "('brand', 'AMPEX 1800'),"
      + "('brand', 'AMPEX 2020'),"
      + "('brand', 'AMPEX 2500'),"
      + "('brand', 'AMPEX 350'),"
      + "('brand', 'AMPEX 370'),"
      + "('brand', 'AMPEX 406'),"
      + "('brand', 'AMPEX 407'),"
      + "('brand', 'AMPEX 431'),"
      + "('brand', 'AMPEX 444'),"
      + "('brand', 'AMPEX 456'),"
      + "('brand', 'AMPEX 457'),"
      + "('brand', 'AMPEX 467 DAT'),"
      + "('brand', 'AMPEX 478'),"
      + "('brand', 'AMPEX 511'),"
      + "('brand', 'AMPEX 521'),"
      + "('brand', 'AMPEX 531'),"
      + "('brand', 'AMPEX 600'),"
      + "('brand', 'Ampex 611'),"
      + "('brand', 'AMPEX 631'),"
      + "('brand', 'AMPEX 632'),"
      + "('brand', 'AMPEX 641'),"
      + "('brand', 'AMPEX 642'),"
      + "('brand', 'AMPEX 679'),"
      + "('brand', 'AMPEX DAT'),"
      + "('brand', 'AMPEX EDR'),"
      + "('brand', 'AMPEX ELN'),"
      + "('brand', 'AMPEX GM'),"
      + "('brand', 'AMPEX GM3600'),"
      + "('brand', 'AMPEX GMI'),"
      + "('brand', 'AMPEX PLUS'),"
      + "('brand', 'AMPEX UDR'),"
      + "('brand', 'Anorgana Geno 1on Typ'),"
      + "('brand', 'Aristocrat'),"
      + "('brand', 'ARMSTRONG AUDIO'),"
      + "('brand', 'Astropulse'),"
      + "('brand', 'AUDIO DIMENSION'),"
      + "('brand', 'Audio Magnetics'),"
      + "('brand', 'AUDIO MAGNETICS CORPORATION'),"
      + "('brand', 'AUDIOMASTERS CORPORATION'),"
      + "('brand', 'AUDIOSONIC'),"
      + "('brand', 'audiotape'),"
      + "('brand', 'audiotape Q19'),"
      + "('brand', 'AUSTRALIAN HANIMEX'),"
      + "('brand', 'AVC'),"
      + "('brand', 'Award'),"
      + "('brand', 'BASF'),"
      + "('brand', 'BASF Chromdioxid'),"
      + "('brand', 'BASF chromdioxid super'),"
      + "('brand', 'BASF Chromdioxid Super II'),"
      + "('brand', 'BASF Chrome Extra II'),"
      + "('brand', 'BASF Chrome MaximaII'),"
      + "('brand', 'BASF CHROME SUPER II'),"
      + "('brand', 'BASF CR-M II'),"
      + "('brand', 'BASF DAT'),"
      + "('brand', 'BASF DP'),"
      + "('brand', 'BASF DP 26'),"
      + "('brand', 'BASF DP 26 LH'),"
      + "('brand', 'BASF DP26'),"
      + "('brand', 'BASF Ferro Extra I'),"
      + "('brand', 'BASF ferro maxima I'),"
      + "('brand', 'BASF Ferro Super I'),"
      + "('brand', 'BASF Ferro Super LH I'),"
      + "('brand', 'BASF ferro super LHI'),"
      + "('brand', 'BASF hifi'),"
      + "('brand', 'BASF LANGSPIELBAND'),"
      + "('brand', 'BASF LGH'),"
      + "('brand', 'BASF LGH 30 P'),"
      + "('brand', 'BASF LGR'),"
      + "('brand', 'BASF LGR 30 P'),"
      + "('brand', 'BASF LGR 35'),"
      + "('brand', 'BASF LGR P'),"
      + "('brand', 'BASF LGR P 30'),"
      + "('brand', 'BASF LGS'),"
      + "('brand', 'BASF LGS 26'),"
      + "('brand', 'BASF LGS 35'),"
      + "('brand', 'BASF LGS 52'),"
      + "('brand', 'BASF LH'),"
      + "('brand', 'BASF LH 90'),"
      + "('brand', 'BASF LH extra I'),"
      + "('brand', 'BASF LH SM'),"
      + "('brand', 'BASF LH Super'),"
      + "('brand', 'BASF LH SUPER 1'),"
      + "('brand', 'BASF LH Super I'),"
      + "('brand', 'BASF LH-EI'),"
      + "('brand', 'BASF LH-MI'),"
      + "('brand', 'BASF LHSM'),"
      + "('brand', 'BASF LN'),"
      + "('brand', 'BASF LN super 1'),"
      + "('brand', 'BASF LN super I'),"
      + "('brand', 'BASF LP'),"
      + "('brand', 'BASF LP35'),"
      + "('brand', 'BASF LPR 35'),"
      + "('brand', 'BASF LR 56'),"
      + "('brand', 'BASF PEM 369'),"
      + "('brand', 'BASF PEM 468'),"
      + "('brand', 'BASF PER 368'),"
      + "('brand', 'BASF PES 18'),"
      + "('brand', 'BASF SM'),"
      + "('brand', 'BASF SM 468'),"
      + "('brand', 'BASF SM 911'),"
      + "('brand', 'BASF SP 52'),"
      + "('brand', 'BASF SP50 LH'),"
      + "('brand', 'BASF SP54 R'),"
      + "('brand', 'BASF SP55 R'),"
      + "('brand', 'BASF SPR 50'),"
      + "('brand', 'BASF SPR 50 LH'),"
      + "('brand', 'BASF SPR 50 LHL'),"
      + "('brand', 'BASF TP 18 LH'),"
      + "('brand', 'BASF TYP LGN'),"
      + "('brand', 'BASF TYP LGS'),"
      + "('brand', 'BASF Typ LGS 26'),"
      + "('brand', 'BASF TYP LGS 52'),"
      + "('brand', 'BEL CLEER'),"
      + "('brand', 'BITCO'),"
      + "('brand', 'Brand 5'),"
      + "('brand', 'Brand Five'),"
      + "('brand', 'CAPITOL'),"
      + "('brand', 'certron'),"
      + "('brand', 'certron HE90'),"
      + "('brand', 'CFS Westinghouse-SPRcolor'),"
      + "('brand', 'Chapple'),"
      + "('brand', 'Compact Cassette'),"
      + "('brand', 'CONCERTAPE'),"
      + "('brand', 'Concorde'),"
      + "('brand', 'CONTRAST'),"
      + "('brand', 'CORONET HE'),"
      + "('brand', 'CORONET LN'),"
      + "('brand', 'Craig'),"
      + "('brand', 'CREST INTERNATIONAL'),"
      + "('brand', 'Crystal'),"
      + "('brand', 'cts'),"
      + "('brand', 'DENON'),"
      + "('brand', 'DENON DX'),"
      + "('brand', 'DENON DX1'),"
      + "('brand', 'DENON DX8'),"
      + "('brand', 'DENON LX'),"
      + "('brand', 'DEUTSCHE WELLE'),"
      + "('brand', 'Dick Smith'),"
      + "('brand', 'DICK SMITH EDR'),"
      + "('brand', 'Dindy'),"
      + "('brand', 'Dindy Black'),"
      + "('brand', 'Dindy Super'),"
      + "('brand', 'Dokorder'),"
      + "('brand', 'Dominion'),"
      + "('brand', 'Douglas Hi-Fi'),"
      + "('brand', 'duCros'),"
      + "('brand', 'EASTMAN KODAK'),"
      + "('brand', 'E-LITE'),"
      + "('brand', 'EMI'),"
      + "('brand', 'EMI Hi dynamic'),"
      + "('brand', 'EMITAPE'),"
      + "('brand', 'EMITAPE 100'),"
      + "('brand', 'EMITAPE 4'),"
      + "('brand', 'EMITAPE 5'),"
      + "('brand', 'EMITAPE 88'),"
      + "('brand', 'EMITAPE 88/12EH'),"
      + "('brand', 'EMITAPE 88/6'),"
      + "('brand', 'EMITAPE Afonic'),"
      + "('brand', 'EMITAPE HI-DYNAMIC'),"
      + "('brand', 'EMITAPE HI-DYNAMIC 9'),"
      + "('brand', 'EMITAPE HI-DYNAMIC HLP-9'),"
      + "('brand', 'EMITAPE HI-DYNAMIC HSP6'),"
      + "('brand', 'EMITAPE MAGNETIC'),"
      + "('brand', 'EMITAPE X1000'),"
      + "('brand', 'ferro MASTER UD'),"
      + "('brand', 'Ferrodynamics'),"
      + "('brand', 'Ferrograph-Ampex'),"
      + "('brand', 'FORWARD'),"
      + "('brand', 'FUJI'),"
      + "('brand', 'FUJI DAT'),"
      + "('brand', 'FUJI DR'),"
      + "('brand', 'FUJI DR-I'),"
      + "('brand', 'FUJI FILM'),"
      + "('brand', 'FUJI FILM FL'),"
      + "('brand', 'FUJI FILM FX'),"
      + "('brand', 'FUJI FL'),"
      + "('brand', 'FUJI FR-I'),"
      + "('brand', 'FUJI FR-I Super'),"
      + "('brand', 'FUJI FX-II'),"
      + "('brand', 'FUJI R DAT'),"
      + "('brand', 'Geloso'),"
      + "('brand', 'Gevaert'),"
      + "('brand', 'glatigny'),"
      + "('brand', 'GOLDRING'),"
      + "('brand', 'GOLDRING STUDIO RANGE'),"
      + "('brand', 'Graceline'),"
      + "('brand', 'GREENCORP'),"
      + "('brand', 'GRUNDIG'),"
      + "('brand', 'Grundig TLP2'),"
      + "('brand', 'GTape'),"
      + "('brand', 'GTape 900'),"
      + "('brand', 'GTape High Density'),"
      + "('brand', 'HANIMEX'),"
      + "('brand', 'HCL'),"
      + "('brand', 'HHB'),"
      + "('brand', 'HHb DA113DC'),"
      + "('brand', 'HITACHI'),"
      + "('brand', 'HITACHI DL'),"
      + "('brand', 'HITACHI Lo-D'),"
      + "('brand', 'HITACHI UD'),"
      + "('brand', 'HITACHI ULTRA'),"
      + "('brand', 'HITACHI ULTRA DYNAMIC'),"
      + "('brand', 'HI-TECH'),"
      + "('brand', 'ILFORD'),"
      + "('brand', 'imation'),"
      + "('brand', 'imitation'),"
      + "('brand', 'INTERNATIONAL'),"
      + "('brand', 'IRISH'),"
      + "('brand', 'IRU'),"
      + "('brand', 'KDK'),"
      + "('brand', 'KGC'),"
      + "('brand', 'KLARION'),"
      + "('brand', 'KODAK'),"
      + "('brand', 'KODAVOX'),"
      + "('brand', 'LAFAYETTE'),"
      + "('brand', 'Lancia'),"
      + "('brand', 'Lectra'),"
      + "('brand', 'LOEWE OPTA'),"
      + "('brand', 'M R SOUNDS'),"
      + "('brand', 'magna MAX2'),"
      + "('brand', 'MAGNASOUND'),"
      + "('brand', 'MALLORY'),"
      + "('brand', 'MARSHAL GOLDEN STUDIO'),"
      + "('brand', 'Marshall'),"
      + "('brand', 'MASTERTAPE'),"
      + "('brand', 'MASTERTONE'),"
      + "('brand', 'MAXELL'),"
      + "('brand', 'Maxell 35-90B'),"
      + "('brand', 'MAXELL A35.5'),"
      + "('brand', 'MAXELL A35-7'),"
      + "('brand', 'Maxell A50.5'),"
      + "('brand', 'maxell E25-7'),"
      + "('brand', 'Maxell LN'),"
      + "('brand', 'maxell MX'),"
      + "('brand', 'maxell S-LN'),"
      + "('brand', 'maxell UD'),"
      + "('brand', 'maxell UDI'),"
      + "('brand', 'maxell UDS-II'),"
      + "('brand', 'maxell UL'),"
      + "('brand', 'maxell UR'),"
      + "('brand', 'maxell XL II'),"
      + "('brand', 'maxell XLI'),"
      + "('brand', 'maxell XLI-S'),"
      + "('brand', 'MAX-WELL'),"
      + "('brand', 'Maxwell MX'),"
      + "('brand', 'Melody'),"
      + "('brand', 'MEMOREX'),"
      + "('brand', 'MEMOREX 1800'),"
      + "('brand', 'MEMOREX MRX 2'),"
      + "('brand', 'MEMOREX MRX I'),"
      + "('brand', 'mfp'),"
      + "('brand', 'MIDAS'),"
      + "('brand', 'MITAPE'),"
      + "('brand', 'MUSICWAY AUDIO'),"
      + "('brand', 'NAGU'),"
      + "('brand', 'NATIONAL'),"
      + "('brand', 'National EN'),"
      + "('brand', 'NATIONAL PANASONIC'),"
      + "('brand', 'NATIONAL PANASONIC RT'),"
      + "('brand', 'NATIONAL RT'),"
      + "('brand', 'NATIONAL RT 3'),"
      + "('brand', 'NATIONAL RT 3G'),"
      + "('brand', 'NATIONAL RT 5'),"
      + "('brand', 'NATIONAL RT-5G'),"
      + "('brand', 'NATIONAL RT-7G'),"
      + "('brand', 'No Frills'),"
      + "('brand', 'NORD'),"
      + "('brand', 'NORD BC'),"
      + "('brand', 'NORDIC'),"
      + "('brand', 'OCL'),"
      + "('brand', 'Olympic Technology'),"
      + "('brand', 'OPUS'),"
      + "('brand', 'OPUS UD'),"
      + "('brand', 'OPUS XD1'),"
      + "('brand', 'Pacific'),"
      + "('brand', 'PARAMOUNT'),"
      + "('brand', 'PDQ'),"
      + "('brand', 'PENNCREST'),"
      + "('brand', 'PERMATION'),"
      + "('brand', 'PERMATON'),"
      + "('brand', 'PHILIPS'),"
      + "('brand', 'PHILIPS AV'),"
      + "('brand', 'PHILIPS DP 13'),"
      + "('brand', 'PHILIPS DP 18'),"
      + "('brand', 'PHILIPS DP13'),"
      + "('brand', 'PHILIPS EL 3915'),"
      + "('brand', 'PHILIPS EL3914'),"
      + "('brand', 'PHILIPS EL3915'),"
      + "('brand', 'PHILIPS ER 13'),"
      + "('brand', 'PHILIPS ER 18'),"
      + "('brand', 'PHILIPS FE'),"
      + "('brand', 'PHILIPS FE I'),"
      + "('brand', 'PHILIPS FS'),"
      + "('brand', 'PHILIPS LP 10'),"
      + "('brand', 'PHILIPS LP 13'),"
      + "('brand', 'PHILIPS LP 15'),"
      + "('brand', 'PHILIPS LP 18'),"
      + "('brand', 'PRINZ'),"
      + "('brand', 'PRO DISC'),"
      + "('brand', 'PULSAR'),"
      + "('brand', 'PURVISONIC'),"
      + "('brand', 'Philips SP18'),"
      + "('brand', 'Pinnacle'),"
      + "('brand', 'PYRAL'),"
      + "('brand', 'PYROX'),"
      + "('brand', 'PYROX MAGICTAPE'),"
      + "('brand', 'QANTEM'),"
      + "('brand', 'QUANTEGY'),"
      + "('brand', 'RADIANT'),"
      + "('brand', 'Radio Shack'),"
      + "('brand', 'rainbow'),"
      + "('brand', 'Ralec'),"
      + "('brand', 'RALMAR'),"
      + "('brand', 'RALMER'),"
      + "('brand', 'RCA'),"
      + "('brand', 'RCA RED SEAL'),"
      + "('brand', 'REALISTIC'),"
      + "('brand', 'REALISTIC GOLD'),"
      + "('brand', 'REALISTIC LN'),"
      + "('brand', 'REALISTIC SUPERTAPE GOLD'),"
      + "('brand', 'recoton'),"
      + "('brand', 'Red Seal'),"
      + "('brand', 'ROBINS'),"
      + "('brand', 'ROLA'),"
      + "('brand', 'ROLATAPE'),"
      + "('brand', 'ROSS'),"
      + "('brand', 'ROYAL APC'),"
      + "('brand', 'RTC Playrite'),"
      + "('brand', 'RZ'),"
      + "('brand', 'SAISHO'),"
      + "('brand', 'SANYO'),"
      + "('brand', 'SAST'),"
      + "('brand', 'Scotch'),"
      + "('brand', 'Scotch 102'),"
      + "('brand', 'Scotch 111'),"
      + "('brand', 'Scotch 111A'),"
      + "('brand', 'Scotch 150'),"
      + "('brand', 'Scotch 175'),"
      + "('brand', 'Scotch 176'),"
      + "('brand', 'Scotch 177'),"
      + "('brand', 'Scotch 190'),"
      + "('brand', 'Scotch 200'),"
      + "('brand', 'Scotch 202'),"
      + "('brand', 'Scotch 203'),"
      + "('brand', 'Scotch 206'),"
      + "('brand', 'Scotch 207'),"
      + "('brand', 'Scotch 208'),"
      + "('brand', 'Scotch 215'),"
      + "('brand', 'Scotch 250'),"
      + "('brand', 'Scotch 9008'),"
      + "('brand', 'Scotch AV 177'),"
      + "('brand', 'Scotch Boy'),"
      + "('brand', 'Scotch BX'),"
      + "('brand', 'Scotch CLASSIC'),"
      + "('brand', 'Scotch DYNARANGE'),"
      + "('brand', 'Scotch Master'),"
      + "('brand', 'Scotch RB-5'),"
      + "('brand', 'Shamrock'),"
      + "('brand', 'SHARP'),"
      + "('brand', 'SILVER SONIC'),"
      + "('brand', 'silver sound'),"
      + "('brand', 'Silver TRAK UDX'),"
      + "('brand', 'Soni-Tape'),"
      + "('brand', 'SONOCOLOR'),"
      + "('brand', 'SONY'),"
      + "('brand', 'SONY 100'),"
      + "('brand', 'SONY 60'),"
      + "('brand', 'SONY AHF'),"
      + "('brand', 'SONY BHF'),"
      + "('brand', 'SONY C'),"
      + "('brand', 'SONY CHF'),"
      + "('brand', 'SONY DAT'),"
      + "('brand', 'SONY DC'),"
      + "('brand', 'SONY DT DAT'),"
      + "('brand', 'SONY EF'),"
      + "('brand', 'SONY HF'),"
      + "('brand', 'SONY PDP-65'),"
      + "('brand', 'SONY PDP-65C'),"
      + "('brand', 'SONY PR-150'),"
      + "('brand', 'SONY SUPER 150'),"
      + "('brand', 'SONY SUPER 300'),"
      + "('brand', 'SONY UCX'),"
      + "('brand', 'SONY UCX-S'),"
      + "('brand', 'SONY ULH'),"
      + "('brand', 'SONY UX'),"
      + "('brand', 'SONY UX-S'),"
      + "('brand', 'SONY ZX'),"
      + "('brand', 'SOUNDCRAFT'),"
      + "('brand', 'Star'),"
      + "('brand', 'STUDER'),"
      + "('brand', 'SUMMIT'),"
      + "('brand', 'Sunhing'),"
      + "('brand', 'SUPERTAPE GOLD'),"
      + "('brand', 'SUPERTAPE HD'),"
      + "('brand', 'SWEDA'),"
      + "('brand', 'T.D.J'),"
      + "('brand', 'TAMMY'),"
      + "('brand', 'tandberg radio'),"
      + "('brand', 'TARGET'),"
      + "('brand', 'TDK'),"
      + "('brand', 'TDK 90'),"
      + "('brand', 'TDK AD'),"
      + "('brand', 'TDK ADX'),"
      + "('brand', 'TDK AR'),"
      + "('brand', 'TDK ARX'),"
      + "('brand', 'TDK C'),"
      + "('brand', 'TDK D'),"
      + "('brand', 'TDK DA-R DAT'),"
      + "('brand', 'TDK DA-RXG'),"
      + "('brand', 'TDK F'),"
      + "('brand', 'TDK LN'),"
      + "('brand', 'TDK LX 35'),"
      + "('brand', 'TDK MA-R'),"
      + "('brand', 'TDK MA-X'),"
      + "('brand', 'TDK OD'),"
      + "('brand', 'TDK RC2'),"
      + "('brand', 'TDK SA'),"
      + "('brand', 'TDK SA-X'),"
      + "('brand', 'TDK SD'),"
      + "('brand', 'TDK SF'),"
      + "('brand', 'TDK Super Dynamic 1200 - SD'),"
      + "('brand', 'That''s'),"
      + "('brand', 'TDK Super Dynamic 1200-SD'),"
      + "('brand', 'TDK-E Synchroreel'),"
      + "('brand', 'TEAC'),"
      + "('brand', 'TEAC SOUND 52'),"
      + "('brand', 'TELEX'),"
      + "('brand', 'TEMPEST'),"
      + "('brand', 'That''s'),"
      + "('brand', 'thunder'),"
      + "('brand', 'TIANTAN'),"
      + "('brand', 'TONEX'),"
      + "('brand', 'TONEX Pastels'),"
      + "('brand', 'Toshiba'),"
      + "('brand', 'Tower'),"
      + "('brand', 'TRANSONIC'),"
      + "('brand', 'tronictape'),"
      + "('brand', 'TSL D'),"
      + "('brand', 'Ultra Sound'),"
      + "('brand', 'Unic'),"
      + "('brand', 'Unknown'),"
      + "('brand', 'VERBATIM'),"
      + "('brand', 'VIbrant'),"
      + "('brand', 'VIVA'),"
      + "('brand', 'W & G'),"
      + "('brand', 'WHSMITH'),"
      + "('brand', 'WORLD SLN'),"
      + "('brand', 'YASHIMA UFOI'),"
      + "('brand', 'ZENITH'),"
      + "('brand', 'EMITAPE 99'),"
      + "('brand', 'TEAC CDX'),"
      + "('brand', 'Dictasette'),"
      + "('brand', 'Zonal'),"
      + "('brand', 'TDK GX 35-90B'),"
      + "('brand', 'AMPEX 541'),"
      + "('brand', 'AMPEX 434'),"
      + "('brand', 'ORWO CR 35'),"
      + "('brand', 'Scotch RB-7'),"
      + "('brand', 'Scotch 220'),"
      + "('brand', 'PHILLIPS CD'),"
      + "('brand', 'ORWO'),"
      + "('brand', 'EMI Super'),"
      + "('brand', 'esc'),"
      + "('brand', 'BASF Ferro POWER I'),"
      + "('brand', 'TDK LX 50-60B'),"
      + "('brand', 'JVC MC-60SF'),"
      + "('durationType', 'Default'),"
      + "('durationType', 'Input'),"
      + "('equalisation', 'IEC'),"
      + "('equalisation', 'NAB'),"
      + "('samplingRate', '11000'),"
      + "('samplingRate', '22050'),"
      + "('samplingRate', '24000'),"
      + "('samplingRate', '32000'),"
      + "('samplingRate', '44100'),"
      + "('samplingRate', '48000'),"
      + "('samplingRate', '88200'),"
      + "('samplingRate', '96000'),"
      + "('samplingRate', '176400'),"
      + "('samplingRate', '192000'),"
      + "('soundField', 'Stereo'),"
      + "('soundField', 'Mono'),"  
      + "('soundField', 'Two Track Mono'),"
      + "('componentLevel','Class'),"
      + "('componentLevel','Collection'),"
      + "('componentLevel','File'),"
      + "('componentLevel','Fonds'),"
      + "('componentLevel','Otherlevel'),"
      + "('componentLevel','Subfonds'),"
      + "('componentLevel','Recordgrp'),"
      + "('componentLevel','Subgrp'),"   
      + "('componentLevel','Series'),"
      + "('componentLevel','Subseries'),"
      + "('bookJournalLevel', 'Issue'),"
      + "('bookJournalLevel', 'Volume'),"
      + "('subUnitType','Additional Material'),"
      + "('subUnitType','Article'),"
      + "('subUnitType','Attachment'),"
      + "('subUnitType','Bibliography'),"
      + "('subUnitType','Biography'),"
      + "('subUnitType','Board leaf'),"
      + "('subUnitType','Book'),"
      + "('subUnitType','Booklet'),"
      + "('subUnitType','Box'),"
      + "('subUnitType','Chapter'),"     
      + "('subUnitType','Clipping'),"
      + "('subUnitType','Compilation'),"     
      + "('subUnitType','Cover'),"
      + "('subUnitType','Cover - Back'),"
      + "('subUnitType','Cover - Front'),"
      + "('subUnitType','Cover - Inside Front '),"
      + "('subUnitType','Cover - Variant'),"
      + "('subUnitType','Cover - Inside Back '),"
      + "('subUnitType','Dedication'),"
      + "('subUnitType','Discography'),"
      + "('subUnitType','Enclosure'),"
      + "('subUnitType','End Papers'),"
      + "('subUnitType','Envelope'),"
      + "('subUnitType','Fly Leaf'),"
      + "('subUnitType','Folder'),"
      + "('subUnitType','Folio'),"
      + "('subUnitType','Foredge'),"
      + "('subUnitType','Game board'),"
      + "('subUnitType','Game instructions'),"
      + "('subUnitType','Game pieces'),"
      + "('subUnitType','Head'),"
      + "('subUnitType','Illustration'),"
      + "('subUnitType','Index'),"
      + "('subUnitType','Interview'),"     
      + "('subUnitType','Introduction'),"
      + "('subUnitType','Invitation'),"
      + "('subUnitType','Issue'),"
      + "('subUnitType','Item'),"
      + "('subUnitType','Map'),"
      + "('subUnitType','Number'),"
      + "('subUnitType','Obverse'),"
      + "('subUnitType','Page'),"
      + "('subUnitType','Page - Additional'),"
      + "('subUnitType','Page - Additional Title'),"
      + "('subUnitType','Page - Contents '),"
      + "('subUnitType','Page - List Title'),"
      + "('subUnitType','Page - Title '),"
      + "('subUnitType','Page - Unnumbered'),"
      + "('subUnitType','Part'),"
      + "('subUnitType','Piece'),"      
      + "('subUnitType','Plate'),"
      + "('subUnitType','Plate - Leaf'),"
      + "('subUnitType','Plate - Verso'),"
      + "('subUnitType','Plates - List'),"
      + "('subUnitType','Port'),"
      + "('subUnitType','Preface'),"
      + "('subUnitType','Program'),"
      + "('subUnitType','Recto'),"
      + "('subUnitType','Reverse'),"
      + "('subUnitType','Section'),"
      + "('subUnitType','Segment'),"    
      + "('subUnitType','Session'),"
      + "('subUnitType','Spine'),"
      + "('subUnitType','State'),"
      + "('subUnitType','Table Of Contents'),"
      + "('subUnitType','Tail'),"
      + "('subUnitType','Text block'),"
      + "('subUnitType','Tile'),"
      + "('subUnitType','Title page verso'),"
      + "('subUnitType','Tour'),"
      + "('subUnitType','Verso'),"
      + "('subUnitType','Volume'),"
      + "('form','Book'),"
      + "('form','Journal'),"
      + "('form','Multi Volume Book'),"
      + "('form','Manuscript'),"
      + "('form','Map'),"
      + "('form','Music'),"
      + "('form','Picture'),"    
      + "('form','Sound recording'),"
      + "('form','Other - Australian'),"
      + "('form','Other - General'),"
      + "('form','Internal photograph'),"
      + "('form','Conservation'),"
      + "('form','Digital Publication'),"
      + "('bibLevel','Set'),"
      + "('bibLevel','Item'),"
      + "('bibLevel','Part'),"
      + "('digitalStatus','Captured'),"
      + "('digitalStatus','Not Captured'),"
      + "('digitalStatus','Partially Captured'),"
      + "('digitalStatus','Preserved analogue'),"
      + "('encodingLevel','Master Copy'),"
      + "('encodingLevel','# - Full level'),"
      + "('encodingLevel','1 - Full level, material not examined'),"
      + "('encodingLevel','2 - Less-than-full level, material not examined'),"
      + "('encodingLevel','3 - Abbreviated level'),"
      + "('encodingLevel','4 - Core level'),"
      + "('encodingLevel','5 - Partial (preliminary) level'),"
      + "('encodingLevel','7 - Minimal level'),"
      + "('encodingLevel','8 - Prepublication level'),"
      + "('encodingLevel','u - Unknown'),"
      + "('encodingLevel','z - Not applicable'),"
      + "('encodingLevel','None'),"
      + "('encodingLevel','Card only'),"
      + "('encodingLevel','Collection level'),"
      + "('encodingLevel','Collection in process'),"
      + "('encodingLevel','Conditions vary'),"
      + "('encodingLevel','Full in process'),"
      + "('encodingLevel','nothing'),"
      + "('genre','Interview'),"
      + "('genre','Speech'),"
      + "('genre','Conference'),"
      + "('genre','Festival'),"
      + "('genre','Lecture'),"
      + "('genre','Monologue'),"
      + "('genre','Other'),"
      + "('publicationCategory','Press Club'),"
      + "('publicationCategory','Radio'),"
      + "('publicationCategory','Commercial'),"
      + "('publicationCategory','Master Copy'),"
      + "('publicationCategory','Other'),"      
      + "('subject','National Library - Products'),"
      + "('subject','National Library - Tapestries'),"
      + "('subject','National Library - Volunteers - [name]'),"
      + "('subject','National Library - Publications - [name]'),"
      + "('subject','National Library - Volunteers - [name]'),"
      + "('subject','National Library - Visits - [name]'),"
      + "('subject','National Library - Building - Exterior - Art'),"
      + "('subject','National Library - Building - Exterior - 1990s'),"
      + "('subject','National Library - Building - Exterior - 2000s'),"
      + "('subject','National Library - Building - Exterior - 2010s'),"
      + "('subject','National Library - Building - Interior - [name]'),"
      + "('subject','National Library - Building - Warehouses and Annexes'),"
      + "('subject','National Library - Committees - [name]'),"
      + "('subject','National Library - Conferences/Seminars/Workshops - [name]'),"
      + "('subject','National Library - Consultants and Contractors - [name]'),"
      + "('subject','National Library - Council - Group and General Photographs'),"
      + "('subject','National Library - Council - Portrait of Individual Member - [name]'),"
      + "('subject','National Library - Donors - [name]'),"
      + "('subject','National Library - Events - [name]'),"
      + "('subject','National Library - Exhibitions - [name]'),"
      + "('subject','National Library - Exhibitions - National Treasures from Australia''s Great Libraries'),"
      + "('subject','National Library - Friends'),"
      + "('subject','National Library - Harold White Fellows - [name]'),"
      + "('subject','National Library - Kenneth Myer Lecture'),"
      + "('subject','National Library - National Folk Festival Fellows - [name]'),"
      + "('subject','National Library - Norman McCann Summer Scholars - [name]'),"
      + "('subject','National Library - Oral History Interview - [name of interviewee]'),"
      + "('subject','National Library - Staff - [name]'),"
      + "('subject','[Institution] - Collection material'),"
      + "('subject','National Library - Social Club'),"
      + "('subject','Events outside the National Library - [name]'),"
      + "('constraint','Copyright'),"
      + "('constraint','Adult content'),"
      + "('constraint','Indigenous'),"
      + "('constraint','Free-of-charge'),"
      + "('constraint','Pending'),"
      + "('constraint','Written permission required'),"
      + "('constraint','Thumbnails only'),"
      + "('constraint','Closed'),"
      + "('constraint','Indigenous - male'),"
      + "('constraint','OH/SPATS'),"
      + "('constraint','Error during migration'),"
      + "('digitalStatus','Captured'),"
      + "('digitalStatus','Not Captured'),"
      + "('digitalStatus','Partially Captured'),"
      + "('digitalStatus','Preserved analogue'),"
      + "('exposureTime', '1/100 at f/2.8'),"
      + "('exposureMode', 'Auto'),"
      + "('exposureMode', 'Manual'),"
      + "('isoSpeedRating', '100'),"
      + "('isoSpeedRating', '400'),"
      + "('isoSpeedRating', '800'),"
      + "('isoSpeedRating', '1600'),"
      + "('focalLenth', '24.0mm'),"
      + "('meteringMode', 'Evaluative'),"
      + "('whiteBalance', 'Auto'),"
      + "('whiteBalance', 'Manual'),"
      + "('tempHolding', 'Yes'),"
      + "('tempHolding', 'No'),"
      + "('digitalSourceType', 'Original digital capture of a real life scene'),"
      + "('digitalSourceType', 'Digitised from a negative on film'),"
      + "('digitalSourceType', 'Digitised from a positive on film'),"
      + "('digitalSourceType', 'Digitised from a print on non-transparent medium'),"
      + "('digitalSourceType', 'Created by software'),"
      + "('sensitiveMaterial', 'Yes'),"
      + "('sensitiveMaterial', 'No'),"
      + "('sensitiveReason', 'Indigenous - male only'),"
      + "('sensitiveReason', 'Indigenous - female only'),"
      + "('sensitiveReason', 'Indigenous - community only'),"
      + "('sensitiveReason', 'Offensive content'),"
      + "('sensitiveReason', 'Disturbing content'),"
      + "('rdsAcknowledgementType', 'Donation of material'),"
      + "('rdsAcknowledgementType', 'Lending of material'),"
      + "('rdsAcknowledgementType', 'Donation of digitised copy'),"
      + "('rdsAcknowledgementType', 'Sponsor')"
    )
    public abstract void seedKeyCodeList();
    
    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
    + "('eadUpdateReviewRequired', 'Y', 'Yes'),"
    + "('eadUpdateReviewRequired', 'N', 'No')")
    public abstract void seedEADUpdateReviewRequired();
    
    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
    + "('eadFileValidationMsg', 'INVALID_FILE_NAME', 'The file ${filename} does not match the work''s PI.  Please rename your file to ${workObjId}.xml.'),"  
    + "('eadFileValidationMsg', 'FILE_ALREADY_LOADED', 'File has already been uploaded for job ${jobId}.')," 
    + "('eadFileValidationMsg', 'CANNOT_OPEN_FILE', 'Fail to access file ${filename}.')," 
    + "('eadFileValidationMsg', 'MISSING_EAD_XML_NAMESPACE', 'Invalid EAD file, it is missing EAD xml namespace: ${xmlHeader}.')," 
    + "('eadFileValidationMsg', 'VALID_FILE', '${filename} is a valid file.'),"
    + "('eadFileValidationMsg', 'FAILED_TO_CREATE_CHILD_WORK', 'Failed to create child works from ${workObjId}.xml for work ${workObjId}.'),"
    + "('eadFileValidationMsg', 'NO_UUID_FOR_CHILD_WORK', 'No Archives Space ID specified for component ${nth} work under work ${workObjId} (Archives Space ID: ${componentWorkUUID}).'),"
    + "('eadFileValidationMsg', 'MISSING_CONTAINER_TYPE', 'No container type specified for one of the containers for the component work ${componentWorkObjId} (Archives Space ID: ${componentWorkUUID})'),"
    + "('eadFileValidationMsg', 'NO_EAD_FILE_UPLOADED', 'Failed to complete EAD job ${jobId} as no EAD file is uploaded.'),"
    + "('eadFileValidationMsg', 'FAILED_EXTRACT_FEATURE', 'Failed to extract ${featureType} for the work ${workObjId}.'),"
    + "('eadFileValidationMsg', 'FAILED_EXTRACT_ENTITIIES', 'Failed to extract entity ${nth} for the work ${workObjId}.'),"
    + "('eadFileValidationMsg', 'FAILED_EXTRACT_BIBLIOGRAPHY', 'Failed to map bibliography for the work ${workObjId}.'),"
    + "('eadFileValidationMsg', 'FAILED_EXTRACT_CONTAINERS', 'Failed to map containers for the work ${componentWorkObjId}.'),"
    + "('eadFileValidationMsg', 'FAILED_EXTRACT_DATE_RANGE', 'Failed to extract date range for the component work ${componentWorkObjId} (Archives Space ID: ${componentWorkUUID})'),"
    + "('eadFileValidationMsg', 'FAILED_TO_DETERMINE_START_DATE', 'Failed to extract start date for the component work ${componentWorkObjId} (Archives Space ID: ${componentWorkUUID})')")
    public abstract void seedDataValidationMsgs();
    
    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
    + "('collection','nla.aus', 'Australian'),"
    + "('collection','nla.ms', 'Manuscript'),"
    + "('collection','nla.map', 'Map'),"
    + "('collection','nla.mus', 'Music'),"
    + "('collection','nla.pic', 'Picture'),"
    + "('collection','nla.gen', 'General'),"
    + "('collection','nla.oh', 'Oral history and folklore'),"
    + "('collection','nla.int', 'Internal photograph'),"
    + "('collection','nla.con', 'Conservation'),"
    + "('collection','nla.ld', 'Legal deposit'),"
    + "('collection','nla.gd', 'Government deposit')")
    public abstract void seedCollectionList();

    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
            + "('commercialStatus', 'Commercial', 'Commercial'),"
            + "('commercialStatus', 'NonCommerc', 'Non-commercial')")
    public abstract void seedCommercialStatusList();

    @SqlUpdate("INSERT INTO lookups (name, code, value, deleted) values " +
            "('accessAgreement', 'OpenAccessImmediately', 'Open access immediately', 'N')," +
            "('accessAgreement', 'OpenAccessEmbargoed', 'Open access (embargoed)', 'N')," +
            "('accessAgreement', 'BasicAccess', 'Basic access (as per Copyright Act)', 'N')")
    public abstract void seedAccessAgreementList();

    @SqlUpdate("INSERT INTO lookups (name, code, value, deleted) values " +
            "('accessAgreementReasonForChange', 'Publisher request', 'Publisher request', 'N')," +
            "('accessAgreementReasonForChange', 'Change of rights owner', 'Change of rights owner', 'N')," +
            "('accessAgreementReasonForChange', 'Disputed rights owner', 'Disputed rights owner', 'N')," +
            "('accessAgreementReasonForChange', 'Other', 'Other', 'N')")
    public abstract void seedAccessAgreementReasonForChangeList();

    @SqlUpdate("INSERT INTO lookups (name, code, value, deleted) values " +
            "('accessConditionReasonForChange', 'End of embargo', 'End of embargo', 'N')")
    public abstract void seedAccessConditionReasonForChangeList();

    @SqlUpdate("INSERT INTO lookups (name, code, value, deleted) values " +
            "('commercialStatusReasonForChange', 'No longer commercially available (NLA assessment)', 'No longer commercially available (NLA assessment)', 'N')," +
            "('commercialStatusReasonForChange', 'No longer commercially available (Publisher advice)', 'No longer commercially available (Publisher advice)', 'N')," +
            "('commercialStatusReasonForChange', 'Became commercially available (NLA assessment)', 'Became commercially available (NLA assessment)', 'N')," +
            "('commercialStatusReasonForChange', 'Became commercially available (Publisher advice)', 'Became commercially available (Publisher advice)', 'N')," +
            "('commercialStatusReasonForChange', 'Other', 'Other', 'N')")
    public abstract void seedCommercialStatusReasonForChangeList();

    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
            + "('depositType', 'OnlineLegal', 'Online legal deposit'),"
            + "('depositType', 'OnlineGovernment', 'Online government deposit'),"
            + "('depositType', 'OnlineVoluntary', 'Online voluntary deposit'),"
            + "('depositType', 'OnlineSpecialCollection', 'Online special collection deposit'),"
            + "('depositType', 'OfflineVoluntary', 'Offline voluntary deposit')")
    public abstract void seedDepositTypeList();
    
    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
            + "('copyType', 'p', 'Physical'),"
            + "('copyType', 'd', 'Digitised'),"
            + "('copyType', 'b', 'Born Digital')")
    public abstract void seedCopyTypeList();
    
    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
            + "('colourSpace', '2', 'RGB'),"
            + "('colourSpace', '6', 'YCbCr'),"
            + "('lens', '0/0', 'minimum f-stops are unknown'),"
            + "('lens', '0', 'minimum focal length in mm'),"
            + "('lens', '1', 'maximum focal length in mm'),"
            + "('lens', '2', 'minimum (maximum aperture) f-stop at minimum focal length'),"
            + "('lens', '3', 'minimum (maximum aperture) f-stop at maximum focal length'),"
            + "('whiteBalance', '0', 'auto'),"
            + "('whiteBalance', '1', 'manual'),"
            + "('fileSource', '3', 'DSC')")
    public abstract void seedTiffMetaLuList();
    
    @SqlUpdate("UPDATE lookups SET VALUE = CODE WHERE value is null")
    public abstract void seedValuesForKeyList();
    
    @SqlUpdate("INSERT INTO tools(id, name, resolution, notes, serialNumber, toolTypeId, toolCategoryId, materialTypeId) VALUES"
            + "(1, 'UMAX PowerLook 2100XL', null, 'Used MagicScan', null, 451, 499, 501), "
            + "(2,'Scanview ScanMate F6', null, null, null, 451, 499, 501), "
            + "(3,'AGFA Arcus II', null, null, null, 451, 499, 501), "
            + "(4,'AGFA DuoScan T2000XL + FotoLook', null, null, null, 451, 499, 501), "
            + "(5,'Nikon Super CoolScan 4000ED', null, null, null, 451, 499, 501), "
            + "(6,'PhaseOne Phase FX', null, null, null, 451, 499, 501), "
            + "(7,'Sinar Macroscan', null, null, null, 451, 499, 501), "
            + "(8,'Nikon D1', null, null, null, 451, 499, 501), "
            + "(9,'Canon 20D', null, null, null, 451, 499, 501), "
            + "(10,'Kodak ProBack', null, null, null, 451, 499, 501), "
            + "(11,'Adobe', null, null, null, 453, 500, 501)"
            )
    public abstract void seedToolsList();
    
    @SqlUpdate(
            "INSERT INTO lookups(name, code, value) VALUES"
                    + "('toolType', 'Transmission scanner', 'Transmission scanner'),"
                    + "('toolType', 'Reflective scanner', 'Reflective scanner'),"
                    + "('toolType', 'Word processing', 'Word Processing')"
              )
    public abstract void seedToolTypesLookups();
    
    @SqlUpdate(
            "INSERT INTO lookups(name, code, value) VALUES"
            + "('toolCategory', 'd', 'Device'),"
            + "('toolCategory', 's', 'Software')"        
            )
    public abstract void seedToolCategoriesLookups();
    
    @SqlUpdate(
            "INSERT INTO lookups(name, code, value) VALUES"
            + "('materialType', 'Image', 'Image'),"
            + "('materialType', 'Sound', 'Sound'),"
            + "('materialType', 'Text', 'Text'),"
            + "('materialType', 'Moving Image', 'Moving Image')"
            )
    public abstract void seedMaterialTypesLookups();
    
    @SqlUpdate(
            "INSERT INTO lookups(name, code, value) VALUES"
            + "('manipulation', 'Cropped', 'Cropped'),"
            + "('manipulation', 'Downsized', 'Downsized'),"
            + "('manipulation', 'Enhanced', 'Enhanced'),"
            + "('manipulation', 'Rotated', 'Rotated')"
            )
    public abstract void seedManipulationLookups();
    
    @SqlUpdate("UPDATE tools SET toolTypeId = :toolTypeId where id > 0 and id < 11")
    public abstract void updateToolTypeForToolsGroup1(@Bind("toolTypeId")Long toolTypeId);

    @SqlUpdate("UPDATE tools SET toolTypeId = :toolTypeId where id = 11")
    public abstract void updateToolTypeForToolsGroup2(@Bind("toolTypeId")Long toolTypeId);

    @SqlUpdate("UPDATE tools SET toolCategoryId = :toolCategoryId where id > 0 and id < 11")
    public abstract void updateToolCategoryForToolsGroup1(@Bind("toolCategoryId")Long toolCategoryId);

    @SqlUpdate("UPDATE tools SET toolCategoryId = :toolCategoryId where id = 11")
    public abstract void updateToolCategoryForToolsGroup2(@Bind("toolCategoryId")Long toolCategoryId);

    @SqlUpdate("UPDATE tools SET materialTypeId = :materialTypeId where id > 0 and id < 11")
    public abstract void updateMaterialTypeForToolsGroup1(@Bind("materialTypeId")Long materialTypeId);

    @SqlUpdate("UPDATE tools SET materialTypeId = :materialTypeId where id = 11")
    public abstract void updateMaterialTypeForToolsGroup2(@Bind("materialTypeId")Long materialTypeId);

    @SqlUpdate("INSERT INTO lookups (name, code, value) VALUES"
            + "('creativeCommons', 'CC BY', 'Attribution (CC BY)'),"
            + "('creativeCommons', 'CC BY-SA', 'Attribution-Share Alike (CC BY-SA)'),"
            + "('creativeCommons', 'CC BY-ND', 'Attribution-No Derivatives (CC BY-ND)'),"
            + "('creativeCommons', 'CC BY-NC', 'Attribution-NonCommercial (CC BY-NC'),"
            + "('creativeCommons', 'CC BY-NC-SA', 'Attribution-NonCommercial Share Alike (CC BY-NC-SA)'),"
            + "('creativeCommons', 'CC BY-NC-ND', 'Attribution-NonCommercial-No Derivatives (CC BY-NC-ND)'),"
            + "('creativeCommons', 'all rights reserved copyright', 'No license (all rights reserved copyright)')")
    protected abstract void seedCreativeCommonsLookups();
    
    public void createLookupsSchema() {
        createLookupTable();
        createCarrierAlgorithmTable();
        createLookupsIdIndex();
        createCarrierAlgorithmLinkIdIndex();
        createCarrierAlgorithmIndex();
        createLookupsNameIndex();
        createLookupsNameCodeIndex();
        createToolsTable();
        createToolsIdIndex();
        createToolsToolTypeIdIndex();
        createToolsToolCategoryIdIndex();
        createToolsMaterialTypeIdIndex();
        seedKeyCodeList();
        seedEADUpdateReviewRequired();
        seedDataValidationMsgs();
        seedCollectionList();
        seedCommercialStatusList();
        seedAccessAgreementList();
        seedCopyTypeList();
        seedTiffMetaLuList();
        seedValuesForKeyList();
        seedToolsList();
        seedToolTypesLookups();
        seedToolCategoriesLookups();
        seedMaterialTypesLookups();
        seedDepositTypeList();
        seedManipulationLookups();
        seedAccessAgreementReasonForChangeList();
        seedAccessConditionReasonForChangeList();
        seedCommercialStatusReasonForChangeList();
        seedCreativeCommonsLookups();
    }

    public void setupToolsAssociations(List<ListLu> lookups) {
        List<ListLu> toolTypes = filterLookups("toolType", lookups);
        List<ListLu> toolCategories = filterLookups("toolCategory", lookups);
        List<ListLu> materialTypes = filterLookups("materialType", lookups);
        updateToolTypeForToolsGroup1(getId(toolTypes, "Transmission Scanner"));
        updateToolTypeForToolsGroup2(getId(toolTypes, "Word processing"));
        updateToolCategoryForToolsGroup1(getId(toolCategories, "d"));
        updateToolCategoryForToolsGroup2(getId(toolCategories, "s"));
        updateMaterialTypeForToolsGroup1(getId(materialTypes, "Image"));
        updateMaterialTypeForToolsGroup2(getId(materialTypes, "Text"));
    }
    
    protected List<ListLu> filterLookups(String name, List<ListLu> lookups) {
        List<ListLu> filteredLookup = new ArrayList<>();
        for (ListLu entry : lookups) {
            if (entry.getName().equals(name)) {
                filteredLookup.add(entry);
            }
        }
        return filteredLookup;
    }
    
    protected Long getId(List<ListLu> list, String lbl) {
        if (list == null) return null;
        for (ListLu entry : list) {
             if (lbl.equalsIgnoreCase(entry.getCode()))
                 return (Long) entry.getId();
        }
        return null;
    }
    
    @SqlQuery(
            "SELECT (COUNT(table_name) >= 2) "
            + "FROM INFORMATION_SCHEMA.tables " 
            + "WHERE table_name IN ('LOOKUPS', 'TOOLS', 'lookups', 'tools')")
    public abstract boolean schemaTablesExist();
    
    
    @SqlQuery(
            "SELECT (COUNT(table_name) >= 1 ) "
            + "FROM INFORMATION_SCHEMA.tables " 
            + "WHERE table_name IN ('carrier_algorithm', 'CARRIER_ALGORITHM')")
    public abstract boolean carrierAlgorithmTableExist();
}

